### ISSUE TITLE
Error in Using Private function

### ISSUE THREAD

**Issue by SalemCode8** [kakajansh/echo#1]
E/flutter ( 6180): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 6180): Failed assertion: boolean expression must not be null
E/flutter ( 6180): #0      SocketIoConnector.privateChannel (package:laravel_echo/src/connector/socketio-connector.dart:51:22)
E/flutter ( 6180): #1      Echo.private (package:laravel_echo/laravel_echo.dart:62:27)
E/flutter ( 6180): #2      RestaurantRest.listenForNotification (package:restaurant_restaurant/main.dart:47:13)
E/flutter ( 6180): <asynchronous suspension>
E/flutter ( 6180): #3      new RestaurantRest (package:restaurant_restaurant/main.dart:39:5)
E/flutter ( 6180): #4      main (package:restaurant_restaurant/main.dart:20:23)
E/flutter ( 6180): #5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter ( 6180): #6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by kakajansh** [comment]
should be fixed, closing for now. Feel free to re-open if the error occurs again
