### ISSUE TITLE
Pusher support

### ISSUE THREAD

**Issue by nicolasvahidzein** [kakajansh/echo#13]
Hello. Will you be implementing pusher service support soon?

Thank you for your great contribution.

**Comment by heywhy** [comment]
@nicolasvahidzein There is a PR #11 which I'll be merging in few days from now, the underlying pusher package is [flutter_pusher_client](https://pub.dartlang.org/packages/flutter_pusher_client) which works fine for android but hasn't been tested against iOS. iOS support will be gladly welcomed at [flutter_pusher_client](https://github.com/heywhy/flutter-pusher-client)

Atanda Rasheed

**Comment by heywhy** [comment]
The PR has been merged, I'm waiting on @kakajansh to upload the updates to dart/flutter repository, while we still waiting on that you can depend on the fork [echo](https://github.com/heywhy/echo) by adding:

```
dependencies:
  laravel_echo:
    git:
      url: git://github.com/heywhy/echo.git
```

Atanda Rasheed

**Comment by nicolasvahidzein** [comment]
i'm not an expert, but how can i help? i develop on ios as well so i can look out for issues. Let me know what i can do to help.

**Comment by heywhy** [comment]
The repository for the pusher client is at https://github.com/heywhy/flutter-pusher-client. I'll be glad if you can help.

Atanda Rasheed

**Comment by heywhy** [comment]
The updates has been published already.

Atanda Rasheed
