### ISSUE TITLE
Connect with laravel-websocket

### ISSUE THREAD

**Issue by fabianArlex** [kakajansh/echo#14]
Hi, some way to connect with the laravel web-socket pusher package?, thanks

**Comment by heywhy** [comment]
@fabianArlex There is a PR #11 which I'll be merging in few days from now, the underlying pusher package is [flutter_pusher_client](https://pub.dartlang.org/packages/flutter_pusher_client) which works fine for android but hasn't been tested against iOS. iOS support will be gladly welcomed at [flutter_pusher_client](https://github.com/heywhy/flutter-pusher-client)

Atanda Rasheed

**Comment by heywhy** [comment]
The PR has been merged, I'm waiting on @kakajansh to upload the updates to dart/flutter repository, while we still waiting on that you can depend on the fork [echo](https://github.com/heywhy/echo) by adding:

```
dependencies:
  laravel_echo:
    git:
      url: git://github.com/heywhy/echo.git
```

Atanda Rasheed

**Comment by kakajansh** [comment]
> waiting on @kakajansh to upload the updates to dart/flutter repository

done
