### ISSUE TITLE
project ':flutter_pusher_client' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

### ISSUE THREAD

**Issue by mianazeemdaula** [kakajansh/echo#15]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_pusher_client' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Gradle task assembleDebug failed with exit code 1

**Comment by heywhy** [comment]
Have u been able to resolve this issue?

**Comment by yazanIbrahim** [comment]
the new update of pusher client suppose to solve this issue, if not got to pusher client plugin and edit the kotlin gradle version in the android level gradle to be 1.3.10

**Comment by kharisazhar** [comment]
Solved :
upgrade to this : flutter_pusher_client: ^0.2.1

**Comment by as2a3** [comment]
Solved :
upgrade to this : `flutter_pusher_client: ^0.3.1`
