### ISSUE TITLE
echo and flutter_pusher_client wont integrate

### ISSUE THREAD

**Issue by yaredtsy** [kakajansh/echo#16]
on Presence Channel here function does not work . it says there no member object.and joining and leaving does not work .and on whisper it says cannot find trigger

**Comment by heywhy** [comment]
Is the installed **flutter_pusher_client** dependency up to date?

**Comment by yaredtsy** [comment]
yes flutter_pusher_client: ^0.2.1.

**Comment by yaredtsy** [comment]
on whispher echo send eventname and data on trigger but flutter_pusher_client trigger only accept eventname

**Comment by heywhy** [comment]
you can always report that at [flutter_pusher_client](https://github.com/heywhy/flutter-pusher-client)
