### ISSUE TITLE
Instance with id null not found 

### ISSUE THREAD

**Issue by PedroCM-git** [kakajansh/echo#26]
Hello im using pusher with my flutter app. In debug mode it works fine but when I try it in my release app I get the following in my
sentry client: 

    PlatformException(error, Instance with id null not found, null)

![image](https://user-images.githubusercontent.com/35906679/89027830-85cbc580-d32b-11ea-9faf-ddcb5b893982.png)

Any ideas on what it could be? Thank you.

**Comment by heywhy** [comment]
I’ll suggest you update the pusher client library, as this issue should be fixed there

**Comment by PedroCM-git** [comment]
> I’ll suggest you update the pusher client library, as this issue should be fixed there

Thank you for your answer but even after updating its giving me the same error. Just to clarify the client gets to connect to pusher succesfully and I can send messages, it fails when it receives an event from pusher such chat message.

**Comment by heywhy** [comment]
You should look at this: https://github.com/heywhy/flutter-pusher-client#r8proguard-code-obfuscation

**Comment by PedroCM-git** [comment]
> You should look at this: https://github.com/heywhy/flutter-pusher-client#r8proguard-code-obfuscation

Yeah, that was it. Thanks a lot,
