### ISSUE TITLE
Pusher error joining presence channel

### ISSUE THREAD

**Issue by indigoswann** [kakajansh/echo#34]
Great package.

I am getting. ` Unhandled Exception: NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance getter 'members'.
Receiver: _LinkedHashMap len:1`

when trying to list out the members of a presence channel.  Joining the channel and listening to events works, but listing the users does no work.  Any advice sir?  Thanks in advances

**Comment by chinloyal** [comment]
@indigoswann I would suggest you use this ([pusher_client](https://pub.dev/packages/pusher_client)) with the echo package, all the apis are supported, event the new ones for encrypted channels

**Comment by danielantoniobs** [comment]
> Great package.
> 
> I am getting. ` Unhandled Exception: NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance getter 'members'. Receiver: _LinkedHashMap len:1`
> 
> when trying to list out the members of a presence channel. Joining the channel and listening to events works, but listing the users does no work. Any advice sir? Thanks in advances

found any solution? thanks!
