### ISSUE TITLE
Migrate to nullsafety please

### ISSUE THREAD

**Issue by oengmengthong** [kakajansh/echo#41]

**Comment by nicolasvahidzein** [comment]
We can close this i guess, i had no issues installing this package on a null safe project. Cheers.

**Comment by nicolasvahidzein** [comment]
+1 How can we fix this? Null safety is crucial at this point. Thanks.

**Comment by oengmengthong** [comment]
@nicolasvahidzein  as I think, flutter still uses null safety.  because it helps improve performance. I hope flutter will open project can run both types of library. but currently, if the project uses SDK null safety, all libraries or plugins must be null safety too.

**Comment by SergiiMytakii** [comment]
+++

**Comment by nicolasvahidzein** [comment]
Hey @kakajansh thanks for the new release but we really need null safety more than anything.

**Comment by kakajansh** [comment]
@nicolasvahidzein Please try latest beta version. It supports null-safety 

https://pub.dev/packages/laravel_echo/versions/1.0.0-beta.1

**Comment by nicolasvahidzein** [comment]
Wonderful thanks. Will do. Any news on when pusher Will be doing the same?
