### ISSUE TITLE
Which pusher client

### ISSUE THREAD

**Issue by nicolasvahidzein** [kakajansh/echo#46]
Hello

which pusher client do you recommend?

pusher_client

or 

flutter_pusher_client 

like you mentioned before?

**Comment by kakajansh** [comment]
Recommend `pusher_client` over other alternatives
- Supports null-safety
- Supports channel authorization
- Well maintained

Also Pusher has featured pusher_client on their [twitter](https://twitter.com/pusher/status/1326461845016809473?s=19) and listed at [pusher.com](https://pusher.com/docs/channels/channels_libraries/libraries/#flutter)

**Comment by nicolasvahidzein** [comment]
Makes perfect sense. Thanks.
