### ISSUE TITLE
How to emit msgs to the socket server

### ISSUE THREAD

**Issue by Wissa-Azmy** [kakajansh/echo#6]
Please add a working flutter app example or add the emit method to the readme code

**Comment by kakajansh** [comment]
Added working example, but they are mostly for listening events. If you want to emit event, you can get socket instance. As it uses [socket_io_client](https://pub.dartlang.org/packages/socket_io_client) package you can do something like that:
```dart
echo.socket.emit('message', 'your message here');
```

**Comment by Wissa-Azmy** [comment]
The getter 'socket' isn't defined for the class 'echo'.

**Comment by kakajansh** [comment]
did you update to the latest version?

**Comment by Wissa-Azmy** [comment]
@kakajansh Thank you for your prompt response. You've done a great job indeed in the new version.
The example app you added is awesome as well.
And I see that you've already added the socket getter to the echo class but unfortunately I can't test it due to another issue to which I'll create a new thread since this one is closed.
