### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dayfault** [kakajansh/echo#9]

**Comment by ziostdev** [comment]
Hello,

When I try to connect to the server, nothing happens.

Here's what I tested: 

```dart
  Echo echo = new Echo({
    'broadcaster': 'socket.io',
    'client': IO.io,
    'host': "http://192.168.0.16:6001",
    'autoConnect': true
  });

void initState () {
    super.initState();
    echo.channel('public-channel').listen('TestEvent', (e) =>print(e));
  }
```

On the laravel-echo development server, I don't see any connecting events (everything works with JS).

**Comment by adamanderson86** [comment]
Check out this [https://github.com/rikulo/socket.io-client-dart/issues/28](url)
I was having any issue and this fixed it

**Comment by dayfault** [comment]
@adamanderson86 

Hello,
This

  ```dart
Echo echo = new Echo({
    'broadcaster': 'socket.io',
    'client': IO.io('http://192.168.0.16:6001', <String, dynamic>{'transports': ['websocket']}),
    'host': "http://192.168.0.16:6001",
    'autoConnect': true
  });
```

Does not work.

=> Class 'Socket' has no instance method 'call'.

I want to use Echo library, not socket.io

**Comment by bhargavsejpalindianic** [comment]
Having same issue it shows connected but Listener not working

**Comment by kakajansh** [comment]
@dayfault @bhargavsejpalindianic Did you try creating Echo instance in initState as provided in [example](https://github.com/kakajansh/echo/blob/3310289b0e849adcc00f3faf2e58db3d8051fbde/example/lib/main.dart#L75)

**Comment by bhargavsejpalindianic** [comment]
it just worked problem was in internal server thanks for quick response @kakajansh

**Comment by dayfault** [comment]
@kakajansh 
Hello.

Yes I tried to creating instance in initState, not working.
I can't see any event in Echo console, just

```L A R A V E L  E C H O  S E R V E R

version 1.5.0

⚠ Starting server in DEV mode...

✔  Running at 0.0.0.0 on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!
```


Here is my laravel-echo-server.json :
```json
{
	"authHost": "http://localhost",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "0.0.0.0",
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"subscribers": {
		"http": true,
		"redis": true
	},
	"apiOriginAllow": {
		"allowCors": false,
		"allowOrigin": "",
		"allowMethods": "",
		"allowHeaders": ""
	}
}
```

I tried with an Android Studio lib, it works. Same with JavaScript lib.
But I need to use Flutter.
